version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: appops
      POSTGRES_PASSWORD: appops
      POSTGRES_DB: appops_hub
    ports:
      - "5432:5432"
    volumes:
      - appops_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  appops_pg:
